# Generated by Django 4.2.9 on 2024-01-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicsite', '0003_alter_product_photo1_alter_product_photo2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scientific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('button_text', models.CharField(max_length=85)),
                ('scientific_text', models.CharField(max_length=300)),
                ('doc_photo', models.ImageField(null=True, upload_to='scientific/')),
            ],
        ),
    ]
