# Generated by Django 4.2.9 on 2024-02-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicsite', '0004_scientific'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='active_substance',
            field=models.CharField(max_length=60, null=True, verbose_name='Действующее вещество'),
        ),
        migrations.AddField(
            model_name='product',
            name='amount_in_a_package',
            field=models.IntegerField(null=True, verbose_name='Количество в упаковке'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='compound',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='conditions_for_dispensing_from_pharmacies',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Условия отпуска из аптек'),
        ),
        migrations.AddField(
            model_name='product',
            name='contraindications',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Противопоказания'),
        ),
        migrations.AddField(
            model_name='product',
            name='course_of_administration_and_dosage',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Курс приема и дозировка'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(max_length=60, null=True, verbose_name='Дозировка'),
        ),
        migrations.AddField(
            model_name='product',
            name='indications_for_use',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Показания к применению'),
        ),
        migrations.AddField(
            model_name='product',
            name='pharmachologic_effect',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Фармакологический эффект'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.CharField(max_length=60, null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='product',
            name='release_form',
            field=models.CharField(max_length=60, null=True, verbose_name='Форма выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Побочные действия'),
        ),
        migrations.AddField(
            model_name='product',
            name='special_instructions',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Специальные указания'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Условия хранения'),
        ),
        migrations.AddField(
            model_name='product',
            name='warning',
            field=models.TextField(blank=True, max_length=6000, null=True, verbose_name='Предупреждение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(max_length=100, verbose_name='Страна происхождения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo3',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo4',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo5',
            field=models.ImageField(null=True, upload_to='products/', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('supplement', 'БАДы'), ('medicine', 'Препараты')], max_length=10, verbose_name='Тип'),
        ),
    ]
