# Generated by Django 4.2.9 on 2024-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicsite', '0005_alter_product_options_product_active_substance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientific',
            options={'verbose_name': 'Научная деятельность', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterField(
            model_name='scientific',
            name='button_text',
            field=models.CharField(max_length=85, verbose_name='Текст для кнопки'),
        ),
        migrations.AlterField(
            model_name='scientific',
            name='doc_photo',
            field=models.ImageField(null=True, upload_to='scientific/', verbose_name='Фото сертификата/патента'),
        ),
        migrations.AlterField(
            model_name='scientific',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scientific',
            name='scientific_text',
            field=models.CharField(max_length=300, verbose_name='Описание научной деятельности'),
        ),
    ]
